# -*- coding: utf-8 -*-
"""Untitled51.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FtQzop151JtyWQ50Dx9DAnO-8CLDhEJ5
"""

import pandas as pd
baza={
    "FISH":[   "Aliyev Ali" , "Aliyeva Dilyora"   ],
    "Yoshi":[ "11"   ,'16'   ],
    "Jinsi":[ "erkak" ,"ayol"      ],
    "Maktabi":[ "2-maktab" ,"Prezident maktabi"       ],
    "Manzili":[ "Farg'ona shahar" ,"Andijon shahar"      ],
    "Tel raqami":[ "99 302 22 12"  , "91 123 45 67"     ]
}

db=pd.DataFrame(baza)
print(db)

filtr=db[db['Jinsi']=="ayol"]
print(filtr)

filtr=db[(db['Jinsi']=="ayol") & (db["Yoshi"]<"15")]
print(filtr)